# Smart meter configuration for esp home
#
# Merk          Kaifa
# Model         MA105
# Type          1-fase kleinverbruik
# P1 port       RJ-11, 6-pins
# Version       DSMR 4.0 (4.0.5 / 4.0.7)	
# Serial        115200 8N1	
# Inverted 	    Yes
# P1 Telegram   /KFM5

esphome:
  name: dsmr

esp32:
  board: denky32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dsmr Fallback Hotspot"
    password: !secret dsmr_fallback_password
    
  manual_ip:
    static_ip: 192.168.178.10
    gateway: 192.168.178.1
    subnet: 255.255.255.0

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: !secret dsmr_encryption_key

ota:

# Enable Web server.
web_server:
  port: 80

# Enable logging
logger:
  baud_rate: 0
  level: ERROR

globals:
  - id: has_key
    type: bool
    restore_value: no
    initial_value: "false"
    
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Restart switch
switch:
  - platform: restart
    name: "DSMR restart"

uart:
  - baud_rate: 115200
    rx_pin: GPIO21 #D2
    rx_buffer_size: 1700
    id: uart_bus    

dsmr:
  #id: dsmr_instance
  max_telegram_length: 1700
  request_pin: GPIO18
  uart_id: uart_bus
  #crc_check: false

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
    gas_delivered:
      name: "Gas Consumed"
  - platform: dht
    pin: GPIO22
    temperature:
      name: "DSMR Temperature"
      filters:
      - sliding_window_moving_average:
          window_size: 33
          send_every: 11
    humidity:
      name: "DSMR Humidity"
      filters:
      - sliding_window_moving_average:
          window_size: 33
          send_every: 11
    update_interval: 66s   
  - platform: pulse_meter
    pin: GPIO17
    name: "Water Flow"
    unit_of_measurement: "liter/min"
    icon: "mdi:water"
    id: water_flow_rate   
  - platform: pulse_meter
    pin: GPIO17
    name: "Water Pulse Meter"
    id: water_pulse_meter
    unit_of_measurement: "liter/min"
    icon: "mdi:water"
    total:
      name: "Water Meter Total"
      unit_of_measurement: "m³"
      id: water_meter_total
      icon: "mdi:water"
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - multiply: 0.001       

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
