esphome:
  name: esp32cam
  platform: ESP32
  board: esp32cam

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32-cam Fallback Hotspot"
    password: !secret esp32cam_fallback_password

captive_portal:

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

ota:

# Enable Web server.
web_server:
  port: 80
  
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ESP32-cam ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ESP32-cam IP
    ssid:
      name: ESP32-cam SSID
    bssid:
      name: ESP32-cam BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ESP32-cam Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ESP32-cam WiFi Signal
    update_interval: 60s

# Restart switch
switch:
  - platform: restart
    name: "ESP32-cam restart"


# and finally the camera!
esp32_camera:
  name: Front
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1600x1200
  jpeg_quality: 10