substitutions:
  plug_name: laundry_machine
  plug_friendly_name: Laundry Machine
  current_res: "0.00221" # Higher value gives lower watt readout
  voltage_div: "955" # Lower value gives lower voltage readout

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${plug_friendly_name} Fallback Hotspot"
    password: !secret laundry_machine_fallback_password

captive_portal:

# Enable logging.
logger:

# Enable Home Assistant API.
api:

# Enable over-the-air updates.
ota:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
    name: "${plug_friendly_name} button"
    
switch:
- platform: gpio
  name: "${plug_friendly_name} Relay"
  pin: GPIO14
  restore_mode: ALWAYS_ON
- platform: gpio
  name: "${plug_friendly_name} LED_Blue"
  pin: GPIO1
  inverted: True
  restore_mode: ALWAYS_OFF
- platform: gpio
  name: "${plug_friendly_name} LED_Red"
  pin: GPIO13
  inverted: True
  restore_mode: ALWAYS_OFF
  
  
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${plug_friendly_name} Amperage"
      unit_of_measurement: A
      id: "${plug_name}_amperage"
    voltage:
      name: "${plug_friendly_name} Voltage"
      unit_of_measurement: V
      id: "${plug_name}_voltage"
    power:
      name: "${plug_friendly_name} Wattage"
      unit_of_measurement: W
      id: "${plug_name}_wattage"
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${plug_friendly_name} Total Daily Energy"
    power_id: "${plug_name}_wattage"
    id: "${plug_name}_total_daily_wattage"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
      