esphome:
  name: somfy-emu-43342
  platform: ESP8266
  board: d1_mini
  includes:
    - cover_somfy_esp8266.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Somy Emulator Fallback Hotspot"
    password: !secret somfy-emu-43342_fallback_password

# Enable logging.
logger:
  level: DEBUG

# Enable Home Assistant API.
api:

# Enable over-the-air updates.
ota:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time


cover:
- platform: custom
  lambda: |-
    auto somfy_cover = new SomfyCover();
    App.register_component(somfy_cover);
    return {somfy_cover};

  covers:
    - name: "Somfy Cover"
      device_class: shutter
      
custom_component:
  - lambda: |-
      return { new CoverSomfiAPI() };      
