esphome:
  name: vindriktning-001
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret vindriktning-001-encryption-key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vindriktning Air Quality 001"
    password: !secret vindriktning-001-fallback-password

captive_portal:

ota:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Ikea Vindriktning PM2.5 sensor
# https://style.oversubstance.net/2021/08/diy-use-an-ikea-vindriktning-air-quality-sensor-in-home-assistant-with-esphome/
uart:
  rx_pin: D2
  baud_rate: 9600

# BMP280 sensor for temperature and air pressure
i2c:
  sda: D4
  scl: D5

sensor:
  - platform: pm1006
    pm_2_5:
      id: vindriktning_air_quality_001
      name: "Particulate Matter 2.5µm Concentration 001"
      icon: mdi:air-filter
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
  - platform: bmp280
    temperature:
      id: vindriktning_temperature_001
      name: "Temperature"
      oversampling: 16x
      filters:
        - offset: -3.5
    pressure:
      id: vindriktning_air_pressure_001
      name: "Air pressure"
    address: 0x76
    update_interval: 60s