esphome:
  name: watering-master
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watering master Fallback Hotspot"
    password: !secret watering_master_fallback_password
    
  manual_ip:
    static_ip: 192.168.178.193
    gateway: 192.168.178.1
    subnet: 255.255.255.0

# Enable logging.
logger:

# Enable Home Assistant API.
api:

# Enable over-the-air updates.
ota:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time


switch:
  - platform: gpio
    id: watering_1
    name: "Watering 1"
    pin: D1
    icon: mdi:watering-can
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - sensor.integration.reset:  watering_meter_1_m3_last_session
    - delay: 1320s
    - switch.turn_off: watering_1
#  - platform: gpio
#    id: watering_2
#    name: "Watering 2"
#    pin: D2
#    icon: mdi:watering-can
#    restore_mode: ALWAYS_OFF
    
sensor:
  - platform: integration
    id: watering_meter_1_m3_total
    name: "Watering meter 1 m3 total"
    sensor: watering_meter_1_flow
    time_unit: ms
    unit_of_measurement: "m3"
    icon: mdi:water
    accuracy_decimals: 4
    restore: true
    min_save_interval: 11s
    filters:
      - multiply: 0.000002
    
  - platform: integration
    id: watering_meter_1_m3_last_session
    name: "Watering meter 1 m3 last session"
    sensor: watering_meter_1_flow
    time_unit: ms
    unit_of_measurement: "m3"
    icon: mdi:water
    accuracy_decimals: 4
    filters:
      - multiply: 0.000002
    
  - platform: pulse_counter
    id: watering_meter_1_flow
    name: "Watering meter 1 flow"
    pin: D3
    icon: mdi:water-circle
    unit_of_measurement: "m3 per uur"
    update_interval: 11s    
    filters:
    - lambda: return (x / 500.0 / 1000.0) * 60.0;
    total:
      id: watering_meter_1_m3
      name: "Watering meter 1 m3"
      unit_of_measurement: "m3"
      icon: mdi:water
      accuracy_decimals: 4
      filters:
        - multiply: 0.000002  # 500 pulses ~= 1 liter